# Generated by Django 3.1.4 on 2022-10-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('short_bio', models.CharField(max_length=50)),
                ('long_bio', models.CharField(max_length=200)),
                ('advocate_since', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
