# Generated by Django 3.1.4 on 2022-10-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221015_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='company_name',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='advocates_name',
            field=models.ManyToManyField(blank=True, to='api.Advocate'),
        ),
    ]
